namespace Shared.Enums;

public enum TimeLineValue
{
    BOOKING_CONFIRMATION,
    VALET_ASSIGNED_FOR_CHECK_IN,
    VALET_PICKED_UP,
    VEHICLE_CHECKED_IN,
    VALET_ASSIGNED_FOR_CHECK_OUT,
    VEHICLE_CHECKED_OUT,
    VALET_RETURNED,

}
